// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlowCleaningCalculator.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PriceCalculatorFeature : object, Xunit.IClassFixture<PriceCalculatorFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PriceCalculator.feature"
#line hidden
        
        public PriceCalculatorFeature(PriceCalculatorFeature.FixtureData fixtureData, SpecFlowCleaningCalculator_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "PriceCalculator", "A short summary of the feature\r\nPrice of -1 is to indicate an exception", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Calculate Price for Cleaning")]
        [Xunit.TraitAttribute("FeatureTitle", "PriceCalculator")]
        [Xunit.TraitAttribute("Description", "Calculate Price for Cleaning")]
        [Xunit.TraitAttribute("Category", "CleaningCalculation")]
        [Xunit.InlineDataAttribute("-1", "\'false\'", "\'false\'", "\'false\'", "-1", new string[0])]
        [Xunit.InlineDataAttribute("0", "\'false\'", "\'false\'", "\'false\'", "500", new string[0])]
        [Xunit.InlineDataAttribute("1", "\'false\'", "\'false\'", "\'false\'", "520", new string[0])]
        [Xunit.InlineDataAttribute("99", "\'false\'", "\'false\'", "\'false\'", "2480", new string[0])]
        [Xunit.InlineDataAttribute("100", "\'false\'", "\'false\'", "\'false\'", "2500", new string[0])]
        [Xunit.InlineDataAttribute("101", "\'false\'", "\'false\'", "\'false\'", "2515", new string[0])]
        [Xunit.InlineDataAttribute("199", "\'false\'", "\'false\'", "\'false\'", "3985", new string[0])]
        [Xunit.InlineDataAttribute("200", "\'false\'", "\'false\'", "\'false\'", "4000", new string[0])]
        [Xunit.InlineDataAttribute("201", "\'false\'", "\'false\'", "\'false\'", "4010", new string[0])]
        [Xunit.InlineDataAttribute("499", "\'false\'", "\'false\'", "\'false\'", "6990", new string[0])]
        [Xunit.InlineDataAttribute("500", "\'false\'", "\'false\'", "\'false\'", "7000", new string[0])]
        [Xunit.InlineDataAttribute("501", "\'false\'", "\'false\'", "\'false\'", "-1", new string[0])]
        [Xunit.InlineDataAttribute("200", "\'true\'", "\'false\'", "\'false\'", "6400", new string[0])]
        [Xunit.InlineDataAttribute("200", "\'false\'", "\'true\'", "\'true\'", "6400", new string[0])]
        [Xunit.InlineDataAttribute("200", "\'false\'", "\'true\'", "\'false\'", "6000", new string[0])]
        [Xunit.InlineDataAttribute("200", "\'false\'", "\'false\'", "\'true\'", "4800", new string[0])]
        public virtual void CalculatePriceForCleaning(string area, string isDeluxe, string isDoubleWash, string isImpreg, string price, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CleaningCalculation"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("area", area);
            argumentsOfScenario.Add("IsDeluxe", isDeluxe);
            argumentsOfScenario.Add("IsDoubleWash", isDoubleWash);
            argumentsOfScenario.Add("IsImpreg", isImpreg);
            argumentsOfScenario.Add("Price", price);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculate Price for Cleaning", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
 testRunner.Given(string.Format("I have entered an {0}", area), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
 testRunner.And(string.Format("I have also decided if IsDeluxe {0}", isDeluxe), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
 testRunner.And(string.Format("I have also decided if IsDoubleWash {0}", isDoubleWash), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 11
 testRunner.And(string.Format("I have also decided if IsImpreg {0}", isImpreg), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 12
 testRunner.When("I press button Calculate price", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 13
 testRunner.Then(string.Format("The result should be {0}", price), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PriceCalculatorFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PriceCalculatorFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
